language: node_js
node_js:
  - "stable"
  - 6

services:
  - postgresql
  - redis-server

before_install:
  - psql -c 'create database fswd_test;' -U postgres

# env:
#   - CXX=g++-4.8
#
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8

env:
  - SCRIPT=lint
  - SCRIPT=test

script: npm run $SCRIPT
